<a href="https://colab.research.google.com/github/KrzysztofTyszecki/data-science-bootcamp/blob/main/template.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
print ("Hello")

Hello


In [4]:
import numpy as np


In [5]:
np.zeros(shape=(4,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [6]:
np.full(shape=(3,3),fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(start=10,  stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [9]:
A= np.array([1,2,3,4])
B= np.array([3,4,5,-5])

In [10]:
A+B

array([ 4,  6,  8, -1])

In [11]:
A+3

array([4, 5, 6, 7])

In [12]:
np.subtract (A,B)

array([-2, -2, -2,  9])

In [13]:
X= np.array([[1,2],[3,3]])
Y= np.array([[1,1],[0,2]])
print(X)
print(Y)

[[1 2]
 [3 3]]
[[1 1]
 [0 2]]


In [14]:
X*Y

array([[1, 2],
       [0, 6]])

In [15]:
X @ Y

array([[1, 5],
       [3, 9]])

In [16]:
Y @ X

array([[4, 5],
       [6, 6]])

In [17]:
np.random.seed(0)

In [18]:
np.random.randn(10, 4)

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385],
       [ 1.53277921,  1.46935877,  0.15494743,  0.37816252],
       [-0.88778575, -1.98079647, -0.34791215,  0.15634897],
       [ 1.23029068,  1.20237985, -0.38732682, -0.30230275]])

In [19]:
np.random.rand()

0.31542835092418386

In [20]:
np.random.randint(10)

5

In [21]:
np.random.randint(low = 10, high = 101, size = 10)

array([22, 52, 94, 85, 78, 16, 78, 57, 13, 86])

In [22]:
np.random.choice(['pyth', 'java', 'sql'])

np.str_('pyth')

In [23]:
A=np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [24]:
# A[idx], A[start:stop], A[:stop], A[start:]

In [25]:
A[2]

np.int64(2)

In [26]:
A[5:10]

array([5, 6, 7, 8, 9])

In [28]:
A=A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [29]:
A[1]

array([5, 6, 7, 8, 9])

In [31]:
A[:, 4]

array([ 4,  9, 14, 19])

In [33]:
A[1,1]

np.int64(6)

In [34]:
A[0,0]

np.int64(0)

In [35]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [36]:
A[1, 2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [39]:
for row in A:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [40]:
for row in A:
  print(row[0])

0
5
10
15


In [41]:
for item in A.flat:
    print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


In [42]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [43]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [44]:
np.bitwise_or(A < -5, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [45]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [47]:
v1 = np.array([-1, 4])
v1

array([-1,  4])

In [48]:
np.linalg.norm(v1)

np.float64(4.123105625617661)

In [49]:
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2)

np.float64(19.209372712298546)

In [50]:
p = np.array([3, 0])
q = np.array([0, 4])

np.linalg.norm(p - q)

np.float64(5.0)

In [51]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])

np.linalg.norm(p - q)

np.float64(5.0990195135927845)

In [52]:
X = np.array([[5, 3], [3, 9]])
Y = np.array([[1], [-1]])
print(X, '\n')
print(Y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [54]:
Z = np.dot(X, Y)
Z

array([[ 2],
       [-6]])

In [55]:
A = np.array([[2, 4], [-1, 3]])
round(np.linalg.det(A))

10

In [56]:
A = np.array([[2, 4], [-1, 3]])
np.trace(A)

np.int64(5)

In [57]:
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [58]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [59]:
np.set_printoptions(precision=4, suppress=True)

np.dot(A, B)

array([[1., 0.],
       [0., 1.]])

In [60]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [61]:
A = np.array([[2, 4], [1, -1]])
print(A)

[[ 2  4]
 [ 1 -1]]


In [62]:
B = np.array([[10], [-1]])
print(B)

[[10]
 [-1]]


In [63]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
X

array([[1.],
       [2.]])

In [64]:
X.shape

(2, 1)